services:
  - type: web
    name: tesseract-server
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: apt-get update && apt-get install -y tesseract-ocr && pip install -r requirements.txt
    startCommand: gunicorn app:app
